// Copyright 2026 Atakku <https://atakku.dev>
//
// This project is dual licensed under MIT and Apache.

apply from: 'https://raw.githubusercontent.com/Atakku/gradle/v51/neoforge_build.gradle'

project(':server').repositories {
  maven { url = "https://maven.createmod.net" } // Create, Ponder, Flywheel
  maven { url = "https://mvn.devos.one/snapshots" } // Registrate
}

project(':server').dependencies {
  implementation("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
  implementation("net.createmod.ponder:ponder-neoforge:${ponder_version}+mc${minecraft_version}")
  compileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${minecraft_version}:${flywheel_version}")
  runtimeOnly("dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_version}")
  implementation("com.tterrag.registrate:Registrate:${registrate_version}")
}
